x = "Hello World"
x = 50
x = 60.5
x = 3j
x = ["vaibhav", "is", "here"] 
x = ("vaibhav", "is", "here") 
x = range(10)  
x = {"name": "vaibhav", "age": 2} 
x = {"vaibhav", "is", "here"} 
x = frozenset({"vaibhav", "is", "here"}) 
x = True
x = b"vaibhav"
x = bytearray(4) 
x = memoryview(bytes(6)) 
x = None